name: Go Build for Windows

on:
  push:
    branches:
      - clients/gohttp
  pull_request:
    branches:
      - clients/gohttp

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' 

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v -o gohttp.exe ./...

      - name: Run Tests
        run: go test -v ./...
